USE VehicleData;
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO


TRUNCATE TABLE dbo.VehicleData;
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('0',155);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('1',106);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('2',418);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('3',82);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('4',180);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('5',11);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('6',413);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('7',349);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('8',64);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('9',46);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('10',195);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('11',29);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('12',205);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('13',260);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('14',214);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('15',430);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('16',194);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('17',84);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('18',26);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('19',315);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('20',449);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('21',276);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('22',281);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('23',481);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('24',257);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('25',379);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('26',421);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('27',267);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('28',76);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('29',46);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('30',314);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('31',118);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('32',355);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('33',55);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('34',374);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('35',177);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('36',194);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('37',105);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('38',115);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('39',246);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('40',23);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('41',317);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('42',191);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('43',259);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('44',278);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('45',21);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('46',31);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('47',290);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('48',206);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('49',299);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('50',460);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('51',130);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('52',35);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('53',478);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('54',221);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('55',437);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('56',384);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('57',244);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('58',58);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('59',30);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('60',20);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('61',336);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('62',226);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('63',112);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('64',310);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('65',137);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('66',380);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('67',169);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('68',395);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('69',281);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('70',200);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('71',474);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('72',212);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('73',142);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('74',306);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('75',433);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('76',298);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('77',31);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('78',231);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('79',320);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('80',393);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('81',366);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('82',491);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('83',323);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('84',98);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('85',472);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('86',211);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('87',51);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('88',382);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('89',68);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('90',101);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('91',134);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('92',130);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('93',374);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('94',469);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('95',314);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('96',439);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('97',466);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('98',394);
INSERT INTO dbo.VehicleData (Registration, Pollution) VALUES ('99',44);


GO
